spring.datasource.url=jdbc:postgresql://localhost:45432/dev1
spring.datasource.username=user1
spring.datasource.password=user1

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=create-drop

greeting.name=\uC218\uC815
greeting.coffee=${greeting.name} is drinking Cafe Cereza

#droid.id=BB-8
#droid.description=Small, rolling android. Probably doesn't drink coffee.
#
##management.endpoints.web.exposure.include=env, info, health
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
