spring:
  datasource:
    url: jdbc:postgresql://localhost:45432/spring_boot_3_security_jwt
    username: 'bach'
    password: '!Devpass0'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
